---
name: ci
"on": push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            _build
            deps
          key: doesnt_change
      - uses: Swatinem/rust-cache@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25"
          elixir-version: "1.14"
      # - run: rustup install 1.59.0
      # - run: rustup default 1.59.0
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.clean --unused
      - run: mix deps.get
      - run: mix validate
