---
name: ci
"on": push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v3
      - run: erlef/setup-beam@v1
        with:
          - otp-version: "25"
          - elixir-version: "1.14"
      - run: mix dialyzer
